services:
  - type: web
    name: highrise-radio-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: HR_TOKEN
        value: 47c2e8210246ad1c4806a18a33dbdcf899db9e89b2719f5346b6294d3607b4fc
      - key: HR_ROOM_ID
        value: 66cfdc844410d5f4f7dafacd
      - key: HR_OWNER
        value: SXP3
